//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahbaUpdateApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NjitEntities : DbContext
    {
        public NjitEntities()
            : base("name=NjitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProgramSetting> ProgramSettings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VersionClient> VersionClients { get; set; }
        public virtual DbSet<VesionApp> VesionApps { get; set; }
    }
}
