//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahbaUpdateApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramSetting
    {
        public int ID { get; set; }
        public bool ShowBackupFormOnExit { get; set; }
        public string ExpiryDate { get; set; }
        public string LastRunDate { get; set; }
        public string AppUpdatePathExe { get; set; }
    }
}
